version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/container/app/Dockerfile
    container_name: rockar
    volumes:
    - .:/app
    ports:
    - "9191:80"
